-- GENERATED FILE — do not edit by hand.
-- Source: supabase/questions/*.json. Regenerate with:
--   node scripts/build-questions-sql.mjs

insert into questions (category, tier, prompt, options, correct_index, fun_fact) values
-- 🎬 Screen Break
('screen-break',1,'Which movie features the line "I''ll be back"?','["RoboCop","The Terminator","Die Hard","Predator"]',1,'Schwarzenegger lobbied to say "I will be back" — he thought the contraction sounded weak.'),
('screen-break',1,'In Finding Nemo, what kind of fish is Dory?','["Clownfish","Angelfish","Blue tang","Pufferfish"]',2,'After the film, demand for blue tangs spiked so hard that marine biologists issued warnings.'),
('screen-break',1,'Which school does Harry Potter attend?','["Hogwarts","Durmstrang","Beauxbatons","Ilvermorny"]',0,'Durmstrang and Beauxbatons arrive in the fourth book; the American school was invented years later.'),
('screen-break',1,'What is Luke Skywalker''s home planet?','["Naboo","Tatooine","Endor","Hoth"]',1,'Its desert scenes were shot in Tunisia, where a real town called Tataouine lent the name.'),
('screen-break',1,'Which animated film features a snowman named Olaf?','["Moana","Tangled","Frozen","Encanto"]',2,'Olaf was rewritten late in production; an earlier version of him was the villain’s sidekick.'),
('screen-break',1,'In Jurassic Park, which animals are brought back to life?','["Mammoths","Sabre-toothed cats","Giant sloths","Dinosaurs"]',3,'Only fifteen minutes of the film contain dinosaurs, and barely six of those are computer-generated.'),
('screen-break',1,'Which superhero is also known as the Dark Knight?','["Batman","Iron Man","Daredevil","Green Arrow"]',0,'His creators briefly gave him blond hair and a red suit before settling on the bat.'),
('screen-break',1,'Who plays Captain Jack Sparrow?','["Orlando Bloom","Johnny Depp","Javier Bardem","Geoffrey Rush"]',1,'The studio panicked at the performance and asked whether the character was meant to be drunk.'),
('screen-break',1,'Which sitcom is set around a coffee shop called Central Perk?','["Seinfeld","Frasier","Friends","Cheers"]',2,'The orange sofa was found in the studio basement, not bought — it had been in storage for years.'),
('screen-break',1,'In The Lion King, what is Simba''s father called?','["Scar","Rafiki","Zazu","Mufasa"]',3,'Simba is simply Swahili for "lion" — several of the film''s names come straight out of the language.'),
('screen-break',2,'Which series is set at the Dunder Mifflin Paper Company?','["Parks and Recreation","30 Rock","Brooklyn Nine-Nine","The Office"]',3,'The US version was adapted from a UK original that ran only 14 episodes.'),
('screen-break',2,'Who directed both Inception and Oppenheimer?','["Christopher Nolan","Denis Villeneuve","Ridley Scott","James Cameron"]',0,'Nolan famously avoids using a smartphone or email.'),
('screen-break',2,'Who directed Pulp Fiction?','["Quentin Tarantino","Martin Scorsese","Robert Rodriguez","Brian De Palma"]',0,'He wrote it while living in Amsterdam, which is why a character opens the film talking about it.'),
('screen-break',2,'Which studio made Toy Story?','["DreamWorks","Pixar","Illumination","Blue Sky"]',1,'It was the first feature film animated entirely on computers, and it nearly got cancelled midway.'),
('screen-break',2,'Who directed the 1979 film Alien?','["Brian De Palma","James Cameron","Ridley Scott","John Carpenter"]',2,'The sequel went to James Cameron, who pitched it by writing "ALIEN" and adding an S as a dollar sign.'),
('screen-break',2,'Which actor plays Tony Stark in the Marvel films?','["Chris Evans","Mark Ruffalo","Chris Hemsworth","Robert Downey Jr."]',3,'The studio resisted for months; the director fought for him, then let him improvise most of the dialogue.'),
('screen-break',2,'Who directed The Grand Budapest Hotel?','["Wes Anderson","Spike Jonze","Sofia Coppola","Noah Baumbach"]',0,'The hotel exterior is a model, filmed outdoors so the daylight on it would look real.'),
('screen-break',2,'Which series follows the Crawley family at an English country estate?','["Peaky Blinders","Downton Abbey","Bridgerton","The Crown"]',1,'The house is a real one, and its owners still live in a private wing while filming goes on.'),
('screen-break',2,'Who directed Spirited Away?','["Isao Takahata","Makoto Shinkai","Hayao Miyazaki","Mamoru Hosoda"]',2,'He has announced his retirement at least five separate times and gone back to work after each.'),
('screen-break',2,'Which studio''s logo is a mountain ringed by stars?','["Universal","Warner Bros.","Columbia","Paramount"]',3,'The founder sketched it from memory of a mountain near his childhood home in Utah.'),
('screen-break',3,'Which show''s 1983 finale drew over 105 million US viewers?','["Cheers","Seinfeld","M*A*S*H","Dallas"]',2,'It held the record for most-watched broadcast until the 2010 Super Bowl.'),
('screen-break',3,'What is the highest-grossing film of all time (unadjusted)?','["Avengers: Endgame","Titanic","Star Wars: The Force Awakens","Avatar"]',3,'Avatar lost the crown to Endgame in 2019, then re-releases in China put it back on top.'),
('screen-break',3,'Which film was the first non-English winner of Best Picture?','["Parasite","Roma","Amour","Life Is Beautiful"]',0,'It won in 2020, ninety-two ceremonies in — and took Director, Screenplay and International Feature too.'),
('screen-break',3,'Blade Runner was adapted from a novel by which author?','["Isaac Asimov","Philip K. Dick","William Gibson","Arthur C. Clarke"]',1,'He died months before release, having seen only twenty minutes of test footage.'),
('screen-break',3,'How many Academy Awards did Titanic win?','["Nine","Ten","Eleven","Twelve"]',2,'Only two other films have matched that total, and no film has ever beaten it.'),
('screen-break',3,'Which actor has won the most Best Actor Oscars?','["Jack Nicholson","Marlon Brando","Tom Hanks","Daniel Day-Lewis"]',3,'He took three, and between two of them he left acting entirely to train as a shoemaker.'),
('screen-break',3,'Which Star Wars film reached cinemas first?','["A New Hope","The Empire Strikes Back","The Phantom Menace","Return of the Jedi"]',0,'It carried no episode number in 1977; the "Episode IV" crawl was added for a re-release.'),
('screen-break',3,'The film Jaws was based on a novel by whom?','["Michael Crichton","Peter Benchley","Stephen King","Thomas Harris"]',1,'He spent his later years campaigning for shark conservation, saying he regretted the panic.'),
('screen-break',3,'Which film franchise features the character Ethan Hunt?','["James Bond","The Bourne series","Mission: Impossible","John Wick"]',2,'The first five instalments each had a different director, which is rare for a series that long.'),
('screen-break',3,'In which year was the first Academy Awards ceremony held?','["1919","1939","1949","1929"]',3,'It lasted fifteen minutes, the winners were announced three months early, and tickets cost five dollars.'),
('screen-break',4,'Which 1927 film won the first Academy Award for Best Picture?','["Wings","Sunrise","Metropolis","The Jazz Singer"]',0,'Wings is the only fully silent film ever to win Best Picture.'),
('screen-break',4,'In The Matrix, how is Neo first told to "follow the white rabbit"?','["A phone call","A message on his computer","A dream","Graffiti on a wall"]',1,'Seconds later, a rabbit tattoo appears at his door — the film''s first big reality glitch.'),
('screen-break',4,'In Jaws, the mechanical shark was nicknamed…','["Bruce","Nigel","Clive","Trevor"]',0,'It broke down so often that the shark is barely shown, which is why the film is frightening.'),
('screen-break',4,'Who was originally cast as Marty McFly in Back to the Future?','["Corey Feldman","Eric Stoltz","Johnny Depp","C. Thomas Howell"]',1,'He shot for over a month before being replaced, and a few of his takes survive in the finished film.'),
('screen-break',4,'Indiana Jones shoots the swordsman in Raiders because Harrison Ford was…','["Behind schedule","Injured on set","Ill with dysentery","Improvising a joke"]',2,'The scripted fight would have taken three days; he suggested the gun so he could go back to bed.'),
('screen-break',4,'The Wilhelm scream was first heard in a film of which decade?','["1970s","1960s","1940s","1950s"]',3,'It has since been dropped into hundreds of films, usually as a private joke between sound editors.'),
('screen-break',4,'What was the blood in the Psycho shower scene?','["Chocolate syrup","Tomato ketchup","Red poster paint","Beetroot juice"]',0,'The film was shot in black and white, so what mattered was how it ran, not what colour it was.'),
('screen-break',4,'Which actor turned down the role of Neo in The Matrix?','["Brad Pitt","Will Smith","Nicolas Cage","Val Kilmer"]',1,'He made Wild Wild West instead, and has said publicly that he would have ruined the part.'),
('screen-break',4,'The horse head in The Godfather was…','["A rubber prop","A carved model","A real horse head","A papier-mâché head"]',2,'It came from a dog-food plant, and the actor was not told what would be under the sheet.'),
('screen-break',4,'Which film was the first released with a Dolby Digital soundtrack?','["Terminator 2","Jurassic Park","Star Wars","Batman Returns"]',3,'The data was printed in the gaps between the sprocket holes, on film that also carried the old analogue track.'),
-- 🤖 AI & Tech
('ai-tech',1,'What does "www" stand for in a web address?','["World Web Window","Wide World Web","Web World Wide","World Wide Web"]',3,'Its inventor Tim Berners-Lee later said the double-u name was a mistake — nine syllables for three letters.'),
('ai-tech',1,'What does "AI" stand for?','["Artificial Intelligence","Automated Intelligence","Advanced Interface","Applied Computation"]',0,'The term was coined for a 1956 workshop at Dartmouth College.'),
('ai-tech',2,'Which company created ChatGPT?','["Google","OpenAI","Meta","Anthropic"]',1,'Anthropic — maker of Claude — was founded by former OpenAI researchers.'),
('ai-tech',2,'In which decade was the first email sent?','["1960s","1980s","1970s","1990s"]',2,'Ray Tomlinson sent it in 1971 and picked the @ sign to separate user from machine.'),
('ai-tech',3,'What was Google originally called?','["PageFinder","BackRub","SearchPlus","Googol"]',1,'The name referred to the "back links" the engine analyzed. It lasted about a year.'),
('ai-tech',3,'Which AI defeated Go world champion Lee Sedol in 2016?','["Deep Blue","Watson","AlphaGo","Stockfish"]',2,'Move 37 in game two was so unusual that commentators initially assumed it was a mistake.'),
('ai-tech',4,'The first computer "bug" was literally what, found in the Harvard Mark II?','["A beetle","A fly","A cockroach","A moth"]',3,'The 1947 moth was taped into the logbook with the note "first actual case of bug being found".'),
('ai-tech',4,'What was the first item ever sold on eBay?','["A broken laser pointer","A Beanie Baby","A guitar","A wristwatch"]',0,'The founder emailed the buyer to check it was intentional — he collected broken laser pointers.'),
-- 💼 Corporate Survival
('corporate',1,'When a colleague says "let''s circle back", they want to…','["Cancel the project","Book a bigger room","Return to the topic later","Go around the building"]',2,'"Circle back" consistently tops surveys of most-hated office jargon.'),
('corporate',1,'What does "OOO" mean in an auto-reply?','["Out of orbit","Only on occasion","Office open online","Out of office"]',3,'The triple-O auto-reply dates back to Microsoft Exchange in the 1990s.'),
('corporate',2,'What does "EOD" usually mean in work chat?','["End of day","End of discussion","Every other day","Executive on duty"]',0,'Pro tip: whose timezone is "end of day"? Nobody has ever agreed.'),
('corporate',2,'"Low-hanging fruit" refers to…','["Kitchen snacks","Easy wins","Junior employees","Cheap suppliers"]',1,'Orchard workers actually pick low fruit last — it bruises less in the basket.'),
('corporate',3,'What does KPI stand for?','["Key Process Improvement","Known Productivity Index","Key Personnel Initiative","Key Performance Indicator"]',3,'The concept traces back to 1950s French "tableau de bord" management dashboards.'),
('corporate',3,'Which company popularized "20% time" for side projects?','["Google","Microsoft","Apple","IBM"]',0,'Gmail and AdSense both started as 20% projects.'),
('corporate',4,'The QWERTY layout was originally designed partly to…','["Speed up typing","Reduce typewriter jams","Alphabetize keys","Fit smaller desks"]',1,'It spaced out common letter pairs so mechanical arms wouldn''t collide.'),
('corporate',4,'In which decade did the first office cubicle debut?','["1950s","1970s","1960s","1980s"]',2,'Designer Robert Propst called later cramped versions "monolithic insanity" and regretted the invention.'),
-- 📼 Rewind
('rewind',1,'Which 90s virtual pet died if you didn''t feed it?','["Furby","Tamagotchi","Pikachu","Beanie Baby"]',1,'Over 82 million Tamagotchis have been sold; some schools banned them for causing "funerals".'),
('rewind',1,'Finish the title: The Fresh Prince of ___','["Beverly Hills","Brooklyn","Bel-Air","Burbank"]',2,'Will Smith took the role partly to pay off a massive tax bill.'),
('rewind',2,'Which falling-block game came bundled with the original Game Boy?','["Snake","Pac-Man","Breakout","Tetris"]',3,'Bundling Tetris instead of Mario is credited with selling the Game Boy to adults.'),
('rewind',2,'What was Microsoft''s animated paperclip assistant called?','["Clippy","Binky","Pixel","Wordy"]',0,'His official name was Clippit. Almost nobody has ever used it.'),
('rewind',3,'In which year did Google launch?','["1996","2000","1998","2002"]',2,'It started in a rented garage that Google later bought for nostalgia.'),
('rewind',3,'Which group sang "I Want It That Way" (1999)?','["NSYNC","Boyz II Men","Westlife","Backstreet Boys"]',3,'The songwriters barely spoke English — which is why the lyrics famously make no sense.'),
('rewind',4,'What was the best-selling single of the 1990s worldwide?','["Candle in the Wind 1997","...Baby One More Time","My Heart Will Go On","Wannabe"]',0,'Elton John''s Diana tribute sold 33 million copies; he has never performed it again.'),
('rewind',4,'What did the first-ever SMS text message (1992) say?','["Hello","Merry Christmas","Test","Happy New Year"]',1,'Engineer Neil Papworth sent it from a computer — phones couldn''t type text yet.'),
-- 🐸 Extremely Online
('online',1,'What breed of dog is the "Doge" meme?','["Corgi","Akita","Pomeranian","Shiba Inu"]',3,'The real dog, Kabosu, was a rescue from a Japanese puppy mill.'),
('online',1,'What does "LOL" stand for?','["Laughing out loud","Lots of love","Log off later","Loudly on line"]',0,'Countless parents have signed condolence texts "LOL" thinking it meant lots of love.'),
('online',2,'The "Distracted Boyfriend" meme is originally what?','["A movie still","A stock photo","A music video frame","A news photo"]',1,'The same models appear in dozens of stock photos, forming an accidental cinematic universe.'),
('online',2,'Which platform''s logo was a bird until 2023?','["Snapchat","Telegram","Twitter","Tumblr"]',2,'The bird''s official name was Larry, after basketball legend Larry Bird.'),
('online',3,'What was the first YouTube video about?','["A cat playing piano","Elephants at the zoo","A dance tutorial","A video game"]',1,'"Me at the zoo" (2005) is 19 seconds long and still up.'),
('online',3,'Who coined the word "meme" in 1976?','["Douglas Adams","Carl Sagan","Richard Dawkins","Marshall McLuhan"]',2,'He meant it as the cultural equivalent of a gene — cat pictures came later.'),
('online',4,'As of 2020, the most-retweeted post ever was…','["Ellen''s Oscar selfie","A plea for chicken nuggets","An Obama quote","A Japanese billionaire''s cash giveaway"]',3,'Yusaku Maezawa offered ¥100m to random retweeters — 4+ million obliged.'),
('online',4,'Keyboard Cat''s original footage was recorded in which decade?','["1980s","1990s","2000s","2010s"]',0,'Charlie Schmidt filmed his cat Fatso in 1984; the internet found it 23 years later.'),
-- ☕ Fuel
('fuel',1,'Espresso was invented in which country?','["Italy","France","Spain","Brazil"]',0,'The word means "pressed out" — not "express", though it is faster.'),
('fuel',1,'Sushi is traditionally wrapped in…','["Seaweed (nori)","Rice paper","Lettuce","Banana leaf"]',0,'Nori was once scraped off dock posts; now it''s farmed on huge ocean nets.'),
('fuel',2,'Which coffee chain is named after a Moby-Dick character?','["Costa","Peet''s","Starbucks","Lavazza"]',2,'The founders almost named it Pequod, after the ship. "Starbuck" was the first mate.'),
('fuel',2,'Croissants originated in which country?','["France","Belgium","Switzerland","Austria"]',3,'The Viennese kipferl came first; France laminated it with butter and took the credit.'),
('fuel',3,'After water, the most-consumed drink in the world is…','["Tea","Coffee","Beer","Orange juice"]',0,'Roughly 2 billion cups of tea are drunk every day.'),
('fuel',3,'Nutella''s main nut is the…','["Almond","Hazelnut","Peanut","Cashew"]',1,'Nutella uses about a quarter of the world''s hazelnut supply.'),
('fuel',4,'Which country drinks the most coffee per capita?','["USA","Italy","Brazil","Finland"]',3,'Finns average 8–12 kg of coffee per person per year; coffee breaks are protected in many union contracts.'),
('fuel',4,'Carrots were originally mostly what color?','["Purple","Orange","White","Red"]',0,'Dutch growers bred orange carrots in the 1600s, allegedly honoring William of Orange.')
on conflict (category, prompt) where room_id is null do update set
  tier = excluded.tier,
  options = excluded.options,
  correct_index = excluded.correct_index,
  fun_fact = excluded.fun_fact;
