/**
 * GENERATED by scripts/audio/generate.mjs — do not edit by hand.
 *
 * Edit the sound design in scripts/audio/sounds.mjs and rerun the generator
 * (requires ffmpeg). The .webm (Opus) source loops gaplessly and is preferred;
 * the .m4a (AAC) fallback carries encoder padding and seams very slightly.
 */

export interface SoundEntry {
  readonly src: readonly string[];
  readonly durationMs: number;
  readonly loop: boolean;
}

export const SOUNDS = {
  'join-blip': { src: ['/audio/join-blip.webm', '/audio/join-blip.m4a'], durationMs: 220, loop: false },
  'countdown-riser': { src: ['/audio/countdown-riser.webm', '/audio/countdown-riser.m4a'], durationMs: 600, loop: false },
  'category-slam': { src: ['/audio/category-slam.webm', '/audio/category-slam.m4a'], durationMs: 450, loop: false },
  'answer-open': { src: ['/audio/answer-open.webm', '/audio/answer-open.m4a'], durationMs: 350, loop: false },
  'lock': { src: ['/audio/lock.webm', '/audio/lock.m4a'], durationMs: 140, loop: false },
  'reveal-hit': { src: ['/audio/reveal-hit.webm', '/audio/reveal-hit.m4a'], durationMs: 500, loop: false },
  'correct': { src: ['/audio/correct.webm', '/audio/correct.m4a'], durationMs: 500, loop: false },
  'wrong-soft': { src: ['/audio/wrong-soft.webm', '/audio/wrong-soft.m4a'], durationMs: 340, loop: false },
  'track-whoosh': { src: ['/audio/track-whoosh.webm', '/audio/track-whoosh.m4a'], durationMs: 550, loop: false },
  'overtake-whoosh': { src: ['/audio/overtake-whoosh.webm', '/audio/overtake-whoosh.m4a'], durationMs: 600, loop: false },
  'lead-flourish': { src: ['/audio/lead-flourish.webm', '/audio/lead-flourish.m4a'], durationMs: 600, loop: false },
  'streak-3': { src: ['/audio/streak-3.webm', '/audio/streak-3.m4a'], durationMs: 420, loop: false },
  'streak-5': { src: ['/audio/streak-5.webm', '/audio/streak-5.m4a'], durationMs: 550, loop: false },
  'streak-8': { src: ['/audio/streak-8.webm', '/audio/streak-8.m4a'], durationMs: 600, loop: false },
  'final-sting': { src: ['/audio/final-sting.webm', '/audio/final-sting.m4a'], durationMs: 600, loop: false },
  'fanfare': { src: ['/audio/fanfare.webm', '/audio/fanfare.m4a'], durationMs: 600, loop: false },
  'lobby-groove': { src: ['/audio/lobby-groove.webm', '/audio/lobby-groove.m4a'], durationMs: 8000, loop: true },
  'round-base': { src: ['/audio/round-base.webm', '/audio/round-base.m4a'], durationMs: 4000, loop: true },
  'round-drive': { src: ['/audio/round-drive.webm', '/audio/round-drive.m4a'], durationMs: 4000, loop: true },
  'round-urgency': { src: ['/audio/round-urgency.webm', '/audio/round-urgency.m4a'], durationMs: 4000, loop: true },
  'round-dread': { src: ['/audio/round-dread.webm', '/audio/round-dread.m4a'], durationMs: 4000, loop: true },
  'ceremony-bed': { src: ['/audio/ceremony-bed.webm', '/audio/ceremony-bed.m4a'], durationMs: 8000, loop: true },
} as const satisfies Record<string, SoundEntry>;

export type SoundId = keyof typeof SOUNDS;
