/**
 * Renders every sound in sounds.mjs, encodes it twice, and rewrites the
 * runtime manifest.
 *
 * PREREQUISITE: ffmpeg on PATH. This script is dev-time only — it is NOT run
 * by `npm run build`, `npm test`, `npm run dev` or CI. Its outputs
 * (public/audio/*, lib/audio/manifest.ts) are committed.
 *
 *   node scripts/audio/generate.mjs
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { SR, writeWav } from './dsp.mjs';
import { BEDS, STINGS, seed } from './sounds.mjs';

const OUT_DIR = join(process.cwd(), 'public', 'audio');
const MANIFEST = join(process.cwd(), 'lib', 'audio', 'manifest.ts');

const ff = args => execFileSync('ffmpeg', ['-y', '-loglevel', 'error', ...args]);

mkdirSync(OUT_DIR, { recursive: true });
const tmp = mkdtempSync(join(tmpdir(), 'cb-audio-'));

const entries = [];
const all = [
  ...Object.entries(STINGS).map(([id, render]) => ({ id, render, loop: false })),
  ...Object.entries(BEDS).map(([id, render]) => ({ id, render, loop: true })),
];

for (const { id, render, loop } of all) {
  seed(0x51ce0000 + id.length * 7919); // per-sound, stable across runs
  const pcm = render();
  const wav = join(tmp, `${id}.wav`);
  writeWav(wav, pcm);

  ff(['-i', wav, '-c:a', 'libopus', '-b:a', '24k', '-ar', '48000', '-ac', '1', join(OUT_DIR, `${id}.webm`)]);
  ff(['-i', wav, '-c:a', 'aac', '-b:a', '32k', '-ar', '44100', '-ac', '1', join(OUT_DIR, `${id}.m4a`)]);

  entries.push({ id, loop, durationMs: Math.round((pcm.length / SR) * 1000) });
  console.log(`${id.padEnd(18)} ${(pcm.length / SR).toFixed(2)}s ${loop ? 'loop' : 'one-shot'}`);
}

rmSync(tmp, { recursive: true, force: true });

const rows = entries
  .map(
    e =>
      `  '${e.id}': { src: ['/audio/${e.id}.webm', '/audio/${e.id}.m4a'], ` +
      `durationMs: ${e.durationMs}, loop: ${e.loop} },`,
  )
  .join('\n');

writeFileSync(
  MANIFEST,
  `/**
 * GENERATED by scripts/audio/generate.mjs — do not edit by hand.
 *
 * Edit the sound design in scripts/audio/sounds.mjs and rerun the generator
 * (requires ffmpeg). The .webm (Opus) source loops gaplessly and is preferred;
 * the .m4a (AAC) fallback carries encoder padding and seams very slightly.
 */

export interface SoundEntry {
  readonly src: readonly string[];
  readonly durationMs: number;
  readonly loop: boolean;
}

export const SOUNDS = {
${rows}
} as const satisfies Record<string, SoundEntry>;

export type SoundId = keyof typeof SOUNDS;
`,
  'utf8',
);

console.log(`\nwrote ${entries.length} sounds to public/audio and lib/audio/manifest.ts`);
