-- M3 P4 — the bank reaches launch size.
--
-- Pure DML, no DDL, and IDEMPOTENT: the same upsert that seeds a fresh
-- local stack tops up a cloud project that already holds an earlier bank,
-- and re-running it is a no-op. Defines no function, so PostgREST needs no
-- schema reload after it.
--
-- GENERATED FILE — do not edit by hand.
-- Source: supabase/questions/*.json. Regenerate with:
--   node scripts/build-questions-sql.mjs

insert into questions (category, tier, prompt, options, correct_index, fun_fact) values
-- 🎬 Screen Break
('screen-break',1,'Which movie features the line "I''ll be back"?','["RoboCop","The Terminator","Die Hard","Predator"]',1,'Schwarzenegger lobbied to say "I will be back" — he thought the contraction sounded weak.'),
('screen-break',1,'In Finding Nemo, what kind of fish is Dory?','["Clownfish","Angelfish","Blue tang","Pufferfish"]',2,'After the film, demand for blue tangs spiked so hard that marine biologists issued warnings.'),
('screen-break',1,'Which school does Harry Potter attend?','["Hogwarts","Durmstrang","Beauxbatons","Ilvermorny"]',0,'Durmstrang and Beauxbatons arrive in the fourth book; the American school was invented years later.'),
('screen-break',1,'What is Luke Skywalker''s home planet?','["Naboo","Tatooine","Endor","Hoth"]',1,'Its desert scenes were shot in Tunisia, where a real town called Tataouine lent the name.'),
('screen-break',1,'Which animated film features a snowman named Olaf?','["Moana","Tangled","Frozen","Encanto"]',2,'Olaf was rewritten late in production; an earlier version of him was the villain’s sidekick.'),
('screen-break',1,'In Jurassic Park, which animals are brought back to life?','["Mammoths","Sabre-toothed cats","Giant sloths","Dinosaurs"]',3,'Only fifteen minutes of the film contain dinosaurs, and barely six of those are computer-generated.'),
('screen-break',1,'Which superhero is also known as the Dark Knight?','["Batman","Iron Man","Daredevil","Green Arrow"]',0,'His creators briefly gave him blond hair and a red suit before settling on the bat.'),
('screen-break',1,'Who plays Captain Jack Sparrow?','["Orlando Bloom","Johnny Depp","Javier Bardem","Geoffrey Rush"]',1,'The studio panicked at the performance and asked whether the character was meant to be drunk.'),
('screen-break',1,'Which sitcom is set around a coffee shop called Central Perk?','["Seinfeld","Frasier","Friends","Cheers"]',2,'The orange sofa was found in the studio basement, not bought — it had been in storage for years.'),
('screen-break',1,'In The Lion King, what is Simba''s father called?','["Scar","Rafiki","Zazu","Mufasa"]',3,'Simba is simply Swahili for "lion" — several of the film''s names come straight out of the language.'),
('screen-break',2,'Which series is set at the Dunder Mifflin Paper Company?','["Parks and Recreation","30 Rock","Brooklyn Nine-Nine","The Office"]',3,'The US version was adapted from a UK original that ran only 14 episodes.'),
('screen-break',2,'Who directed both Inception and Oppenheimer?','["Christopher Nolan","Denis Villeneuve","Ridley Scott","James Cameron"]',0,'Nolan famously avoids using a smartphone or email.'),
('screen-break',2,'Who directed Pulp Fiction?','["Quentin Tarantino","Martin Scorsese","Robert Rodriguez","Brian De Palma"]',0,'He wrote it while living in Amsterdam, which is why a character opens the film talking about it.'),
('screen-break',2,'Which studio made Toy Story?','["DreamWorks","Pixar","Illumination","Blue Sky"]',1,'It was the first feature film animated entirely on computers, and it nearly got cancelled midway.'),
('screen-break',2,'Who directed the 1979 film Alien?','["Brian De Palma","James Cameron","Ridley Scott","John Carpenter"]',2,'The sequel went to James Cameron, who pitched it by writing "ALIEN" and adding an S as a dollar sign.'),
('screen-break',2,'Which actor plays Tony Stark in the Marvel films?','["Chris Evans","Mark Ruffalo","Chris Hemsworth","Robert Downey Jr."]',3,'The studio resisted for months; the director fought for him, then let him improvise most of the dialogue.'),
('screen-break',2,'Who directed The Grand Budapest Hotel?','["Wes Anderson","Spike Jonze","Sofia Coppola","Noah Baumbach"]',0,'The hotel exterior is a model, filmed outdoors so the daylight on it would look real.'),
('screen-break',2,'Which series follows the Crawley family at an English country estate?','["Peaky Blinders","Downton Abbey","Bridgerton","The Crown"]',1,'The house is a real one, and its owners still live in a private wing while filming goes on.'),
('screen-break',2,'Who directed Spirited Away?','["Isao Takahata","Makoto Shinkai","Hayao Miyazaki","Mamoru Hosoda"]',2,'He has announced his retirement at least five separate times and gone back to work after each.'),
('screen-break',2,'Which studio''s logo is a mountain ringed by stars?','["Universal","Warner Bros.","Columbia","Paramount"]',3,'The founder sketched it from memory of a mountain near his childhood home in Utah.'),
('screen-break',3,'Which show''s 1983 finale drew over 105 million US viewers?','["Cheers","Seinfeld","M*A*S*H","Dallas"]',2,'It held the record for most-watched broadcast until the 2010 Super Bowl.'),
('screen-break',3,'What is the highest-grossing film of all time (unadjusted)?','["Avengers: Endgame","Titanic","Star Wars: The Force Awakens","Avatar"]',3,'Avatar lost the crown to Endgame in 2019, then re-releases in China put it back on top.'),
('screen-break',3,'Which film was the first non-English winner of Best Picture?','["Parasite","Roma","Amour","Life Is Beautiful"]',0,'It won in 2020, ninety-two ceremonies in — and took Director, Screenplay and International Feature too.'),
('screen-break',3,'Blade Runner was adapted from a novel by which author?','["Isaac Asimov","Philip K. Dick","William Gibson","Arthur C. Clarke"]',1,'He died months before release, having seen only twenty minutes of test footage.'),
('screen-break',3,'How many Academy Awards did Titanic win?','["Nine","Ten","Eleven","Twelve"]',2,'Only two other films have matched that total, and no film has ever beaten it.'),
('screen-break',3,'Which actor has won the most Best Actor Oscars?','["Jack Nicholson","Marlon Brando","Tom Hanks","Daniel Day-Lewis"]',3,'He took three, and between two of them he left acting entirely to train as a shoemaker.'),
('screen-break',3,'Which Star Wars film reached cinemas first?','["A New Hope","The Empire Strikes Back","The Phantom Menace","Return of the Jedi"]',0,'It carried no episode number in 1977; the "Episode IV" crawl was added for a re-release.'),
('screen-break',3,'The film Jaws was based on a novel by whom?','["Michael Crichton","Peter Benchley","Stephen King","Thomas Harris"]',1,'He spent his later years campaigning for shark conservation, saying he regretted the panic.'),
('screen-break',3,'Which film franchise features the character Ethan Hunt?','["James Bond","The Bourne series","Mission: Impossible","John Wick"]',2,'The first five instalments each had a different director, which is rare for a series that long.'),
('screen-break',3,'In which year was the first Academy Awards ceremony held?','["1919","1939","1949","1929"]',3,'It lasted fifteen minutes, the winners were announced three months early, and tickets cost five dollars.'),
('screen-break',4,'Which 1927 film won the first Academy Award for Best Picture?','["Wings","Sunrise","Metropolis","The Jazz Singer"]',0,'Wings is the only fully silent film ever to win Best Picture.'),
('screen-break',4,'In The Matrix, how is Neo first told to "follow the white rabbit"?','["A phone call","A message on his computer","A dream","Graffiti on a wall"]',1,'Seconds later, a rabbit tattoo appears at his door — the film''s first big reality glitch.'),
('screen-break',4,'In Jaws, the mechanical shark was nicknamed…','["Bruce","Nigel","Clive","Trevor"]',0,'It broke down so often that the shark is barely shown, which is why the film is frightening.'),
('screen-break',4,'Who was originally cast as Marty McFly in Back to the Future?','["Corey Feldman","Eric Stoltz","Johnny Depp","C. Thomas Howell"]',1,'He shot for over a month before being replaced, and a few of his takes survive in the finished film.'),
('screen-break',4,'Indiana Jones shoots the swordsman in Raiders because Harrison Ford was…','["Behind schedule","Injured on set","Ill with dysentery","Improvising a joke"]',2,'The scripted fight would have taken three days; he suggested the gun so he could go back to bed.'),
('screen-break',4,'The Wilhelm scream was first heard in a film of which decade?','["1970s","1960s","1940s","1950s"]',3,'It has since been dropped into hundreds of films, usually as a private joke between sound editors.'),
('screen-break',4,'What was the blood in the Psycho shower scene?','["Chocolate syrup","Tomato ketchup","Red poster paint","Beetroot juice"]',0,'The film was shot in black and white, so what mattered was how it ran, not what colour it was.'),
('screen-break',4,'Which actor turned down the role of Neo in The Matrix?','["Brad Pitt","Will Smith","Nicolas Cage","Val Kilmer"]',1,'He made Wild Wild West instead, and has said publicly that he would have ruined the part.'),
('screen-break',4,'The horse head in The Godfather was…','["A rubber prop","A carved model","A real horse head","A papier-mâché head"]',2,'It came from a dog-food plant, and the actor was not told what would be under the sheet.'),
('screen-break',4,'Which film was the first released with a Dolby Digital soundtrack?','["Terminator 2","Jurassic Park","Star Wars","Batman Returns"]',3,'The data was printed in the gaps between the sprocket holes, on film that also carried the old analogue track.'),
-- 🤖 AI & Tech
('ai-tech',1,'What does "www" stand for in a web address?','["World Web Window","Wide World Web","Web World Wide","World Wide Web"]',3,'Its inventor Tim Berners-Lee later said the double-u name was a mistake — nine syllables for three letters.'),
('ai-tech',1,'What does "AI" stand for?','["Artificial Intelligence","Automated Intelligence","Advanced Interface","Applied Computation"]',0,'The term was coined for a 1956 workshop at Dartmouth College.'),
('ai-tech',1,'What does "USB" stand for?','["Universal Serial Bus","United System Board","Universal Storage Box","Unified Serial Base"]',0,'Its designer has said the reversible plug was dropped to halve the cost of the connector.'),
('ai-tech',1,'What does "PDF" stand for?','["Public Document Format","Portable Document Format","Printed Document File","Personal Data Folder"]',1,'The format was designed so a page would print identically on any machine — the "paper" was the point.'),
('ai-tech',1,'Which company makes the iPhone?','["Samsung","Nokia","Apple","Sony"]',2,'The first model could not copy and paste text, and had no app store for its first year.'),
('ai-tech',1,'What does GPS help a device work out?','["Its battery level","Its screen size","Its storage space","Its location"]',3,'It works by timing signals from satellites, so a receiver needs an extremely accurate clock.'),
('ai-tech',1,'What does "CPU" stand for?','["Central Processing Unit","Computer Power Utility","Central Program Unit","Core Processing Unit"]',0,'Modern ones spend most of their time waiting for memory rather than actually calculating.'),
('ai-tech',1,'What is the small picture representing an app called?','["A widget","An icon","A cursor","A pixel"]',1,'The desktop metaphor of files, folders and a trash can came out of Xerox research in the 1970s.'),
('ai-tech',1,'Which key combination usually copies text?','["Ctrl + X","Ctrl + V","Ctrl + C","Ctrl + Z"]',2,'Cut, copy and paste sit next to each other on the keyboard for exactly that reason.'),
('ai-tech',1,'What does "URL" stand for?','["Universal Reading Link","Unified Resource Locator","User Registered Location","Uniform Resource Locator"]',3,'The double slash after the colon serves no purpose; its inventor has publicly apologised for it.'),
('ai-tech',2,'Which company created ChatGPT?','["Google","OpenAI","Meta","Anthropic"]',1,'Anthropic — maker of Claude — was founded by former OpenAI researchers.'),
('ai-tech',2,'In which decade was the first email sent?','["1960s","1980s","1970s","1990s"]',2,'Ray Tomlinson sent it in 1971 and picked the @ sign to separate user from machine.'),
('ai-tech',2,'Which company owns the Android operating system?','["Google","Nokia","Microsoft","Samsung"]',0,'It began as a startup aimed at digital cameras, and was bought for a reported fifty million dollars.'),
('ai-tech',2,'Which company created the PlayStation?','["Sega","Sony","Nintendo","Atari"]',1,'It started as a CD add-on for a Nintendo console; the deal collapsed and the add-on became a rival.'),
('ai-tech',2,'Which company created the Java programming language?','["International Business Machines","Oracle Corporation","Sun Microsystems","Netscape Communications"]',2,'Oracle owns it now, but only because it bought the company that built it, years after the fact.'),
('ai-tech',2,'Which social network was started in a Harvard dorm room?','["Twitter","LinkedIn","MySpace","Facebook"]',3,'For its first months you needed a university email address to sign up at all.'),
('ai-tech',2,'Which company makes the Kindle e-reader?','["Amazon","Google","Kobo","Rakuten"]',0,'The screen is not a screen in the usual sense — it moves physical particles and then switches off.'),
('ai-tech',2,'In which decade did the World Wide Web open to the public?','["1970s","1990s","1980s","2000s"]',1,'The proposal was written in 1989 and its manager’s only comment was "vague, but exciting".'),
('ai-tech',2,'Which company sells Photoshop?','["Corel","Autodesk","Adobe","Macromedia"]',2,'Two brothers wrote it to display greyscale images on a Mac, then licensed it rather than sell it outright.'),
('ai-tech',2,'Which company made the first commercially successful web browser?','["Microsoft","Apple","Sun Microsystems","Netscape"]',3,'Its internal codename was Mozilla, which outlived the company and became a browser of its own.'),
('ai-tech',3,'What was Google originally called?','["PageFinder","BackRub","SearchPlus","Googol"]',1,'The name referred to the "back links" the engine analyzed. It lasted about a year.'),
('ai-tech',3,'Which AI defeated Go world champion Lee Sedol in 2016?','["Deep Blue","Watson","AlphaGo","Stockfish"]',2,'Move 37 in game two was so unusual that commentators initially assumed it was a mistake.'),
('ai-tech',3,'Who is credited with writing the first computer program?','["Ada Lovelace","Grace Hopper","Alan Turing","Charles Babbage"]',0,'The machine it was written for was never built, so the program went unrun for over a century.'),
('ai-tech',3,'Who founded Microsoft with Paul Allen?','["Steve Ballmer","Bill Gates","Steve Wozniak","Gordon Moore"]',1,'The company was founded in Albuquerque, not Seattle, and moved north four years later.'),
('ai-tech',3,'In which year did the iPhone first go on sale?','["2005","2006","2007","2008"]',2,'It shipped with no third-party apps at all; developers were told to write websites instead.'),
('ai-tech',3,'Who invented the World Wide Web?','["Vint Cerf","Marc Andreessen","Robert Kahn","Tim Berners-Lee"]',3,'He gave the whole thing away royalty-free, which is the reason anyone could build on it.'),
('ai-tech',3,'Moore''s Law describes the doubling of what?','["Transistors on a chip","Processor clock speed","Hard disk capacity","Network bandwidth"]',0,'It was never a law of physics — it was an observation in a magazine article, later treated as a target.'),
('ai-tech',3,'Which language was created by Guido van Rossum?','["Ruby","Python","Perl","Lua"]',1,'He wrote it over a Christmas break as a hobby project, and named it after a comedy troupe.'),
('ai-tech',3,'In which year did IBM''s Deep Blue beat Garry Kasparov?','["1993","1995","1997","1999"]',2,'Kasparov had beaten the same machine a year earlier, and demanded a rematch that never happened.'),
('ai-tech',3,'What is the binary number 1010 in decimal?','["Eight","Twelve","Six","Ten"]',3,'Each place is worth double the one to its right, so 1010 is simply eight plus two.'),
('ai-tech',4,'The first computer "bug" was literally what, found in the Harvard Mark II?','["A beetle","A fly","A cockroach","A moth"]',3,'The 1947 moth was taped into the logbook with the note "first actual case of bug being found".'),
('ai-tech',4,'What was the first item ever sold on eBay?','["A broken laser pointer","A Beanie Baby","A guitar","A wristwatch"]',0,'The founder emailed the buyer to check it was intentional — he collected broken laser pointers.'),
('ai-tech',4,'What was the first message sent over ARPANET?','["LO","HELLO","TEST","READY"]',0,'They were typing LOGIN when the system crashed, so the first network message was accidental.'),
('ai-tech',4,'What was Amazon nearly called instead?','["Relentless","Cadabra","Bookmart","Aardvark"]',1,'A lawyer heard it as "cadaver" over the phone, which ended that idea quickly.'),
('ai-tech',4,'The name "Bluetooth" comes from a…','["Swedish radio brand","Dutch cable maker","Danish king","Finnish engineer"]',2,'The logo is his initials in runes, which is why it looks like nothing else on your phone.'),
('ai-tech',4,'How many bytes are in a kibibyte?','["1,000","1,004","1,020","1,024"]',3,'The awkward name exists because disk makers count in thousands and operating systems do not.'),
('ai-tech',4,'The first webcam was pointed at what, in Cambridge?','["A coffee pot","A fish tank","A bicycle rack","A front door"]',0,'Researchers were tired of walking downstairs to find it empty; the pot later sold at auction.'),
('ai-tech',4,'Which company turned down buying Google for about $1 million?','["Yahoo","Excite","Lycos","AltaVista"]',1,'Its chief executive thought a search engine that sent people away too fast was bad for business.'),
('ai-tech',4,'What was the first product Nokia ever made?','["Rubber boots","Television sets","Paper","Telephone cable"]',2,'It started as a pulp mill in 1865, and the rubber boots came decades later — those are real too.'),
('ai-tech',4,'What does the brand name "Wi-Fi" actually stand for?','["Wireless Fidelity","Wide Frequency","Wireless Filter","Nothing at all"]',3,'A branding firm invented it to echo Hi-Fi; the "wireless fidelity" slogan was bolted on afterwards.'),
-- 💼 Corporate Survival
('corporate',1,'When a colleague says "let''s circle back", they want to…','["Cancel the project","Book a bigger room","Return to the topic later","Go around the building"]',2,'"Circle back" consistently tops surveys of most-hated office jargon.'),
('corporate',1,'What does "OOO" mean in an auto-reply?','["Out of orbit","Only on occasion","Office open online","Out of office"]',3,'The triple-O auto-reply dates back to Microsoft Exchange in the 1990s.'),
('corporate',1,'A "standup" meeting is supposed to be…','["Short","Annual","Optional","Recorded"]',0,'Standing is the whole mechanism: the discomfort is meant to be the timer.'),
('corporate',1,'What does "ASAP" stand for?','["As Simple As Possible","As Soon As Possible","At Speed And Pace","Always Send A Password"]',1,'It spread through military signal traffic, where every extra character cost transmission time.'),
('corporate',1,'"Touch base" means to…','["Restart a project","Escalate a problem","Have a quick catch-up","Book a meeting room"]',2,'It comes from baseball, where touching the base is the one thing you must not forget to do.'),
('corporate',1,'A meeting invite marked "FYI only" is asking you to…','["Chair the meeting","Take the minutes","Reply within the hour","Read it and do nothing"]',3,'FYI predates email by decades — it was office-memo shorthand long before anyone had an inbox.'),
('corporate',1,'What does "CC" do on an email?','["Copies in other people","Encrypts the message","Deletes it after reading","Sends it to a printer"]',0,'It stands for carbon copy — the flimsy second sheet a typist put behind the original.'),
('corporate',1,'What does "HR" stand for in a company?','["High Regard","Human Resources","Hourly Rates","House Rules"]',1,'The phrase was coined by an economist in 1893, but no company had a department for it until much later.'),
('corporate',1,'"Bandwidth", in office talk, means…','["Internet speed","Meeting room size","Time and capacity","Budget remaining"]',2,'Borrowing it from engineering lets people decline work without ever saying the word no.'),
('corporate',1,'What does "WFH" mean?','["Waiting for handover","Work from head office","Week from Friday","Working from home"]',3,'The abbreviation existed for years as a rare perk before it briefly became the default.'),
('corporate',2,'What does "EOD" usually mean in work chat?','["End of day","End of discussion","Every other day","Executive on duty"]',0,'Pro tip: whose timezone is "end of day"? Nobody has ever agreed.'),
('corporate',2,'"Low-hanging fruit" refers to…','["Kitchen snacks","Easy wins","Junior employees","Cheap suppliers"]',1,'Orchard workers actually pick low fruit last — it bruises less in the basket.'),
('corporate',2,'"Boiling the ocean" describes a plan that is…','["Impossibly broad","Extremely urgent","Poorly funded","Secretly cancelled"]',0,'Consultants use it as a warning; the phrase is often traced to Mark Twain as a joke about ambition.'),
('corporate',2,'On an email, "BCC" hides a recipient from…','["The sender","Everyone else","The mail server","The spam filter"]',1,'Replying all to a message you were blind-copied on is the classic way to reveal yourself.'),
('corporate',2,'"Blue sky thinking" asks a team to…','["Cut costs first","Check the weather","Ignore constraints","Work outdoors"]',2,'The instruction is usually followed within minutes by someone naming the budget.'),
('corporate',2,'A project "post-mortem" exists to do what?','["Assign blame fairly","Approve the budget","Celebrate the launch","Learn what happened"]',3,'Some firms run a "pre-mortem" instead — imagining the failure first, before anything has gone wrong.'),
('corporate',2,'"Take it offline" in a meeting means…','["Discuss it separately","Disconnect the call","Cancel the project","Write it down"]',0,'The phrase survived the move to video calls, where absolutely nothing is offline.'),
('corporate',2,'What does signing an "NDA" stop you doing?','["Working elsewhere","Sharing information","Claiming expenses","Taking annual leave"]',1,'The document that stops you working elsewhere is a different one entirely — a non-compete.'),
('corporate',2,'A "dotted line" report means you also answer to…','["Nobody at all","The board only","A second manager","An outside auditor"]',2,'The name is literal: on the org chart the second relationship is drawn as a dashed line.'),
('corporate',2,'"Scope creep" describes a project that…','["Runs out of money","Loses its sponsor","Finishes too early","Keeps growing"]',3,'It rarely arrives as one big change; it arrives as a series of small reasonable ones.'),
('corporate',3,'What does KPI stand for?','["Key Process Improvement","Known Productivity Index","Key Personnel Initiative","Key Performance Indicator"]',3,'The concept traces back to 1950s French "tableau de bord" management dashboards.'),
('corporate',3,'Which company popularized "20% time" for side projects?','["Google","Microsoft","Apple","IBM"]',0,'Gmail and AdSense both started as 20% projects.'),
('corporate',3,'Which country gave us "karoshi", meaning death from overwork?','["Japan","Korea","China","Taiwan"]',0,'The word entered official use in the 1980s, when the deaths began appearing in labour statistics.'),
('corporate',3,'The Peter Principle says people are promoted until they…','["Retire early","Reach incompetence","Become directors","Leave the company"]',1,'It was published as satire in 1969, then studied seriously and found to hold up rather well.'),
('corporate',3,'Which management approach is Toyota famous for pioneering?','["Six Sigma","Agile","Lean","Waterfall"]',2,'Any worker on the line could halt the whole factory by pulling a cord — that was the point.'),
('corporate',3,'Parkinson''s Law says work expands to fill…','["The nearest deadline","The budget allowed","The team assigned","The time available"]',3,'It appeared in a 1955 magazine essay about the civil service, and was meant as mockery.'),
('corporate',3,'The phrase "think outside the box" comes from…','["A puzzle with nine dots","A shipping industry term","A military training drill","A 1960s advertising slogan"]',0,'The puzzle is solved by drawing past the square the dots imply — a box nobody actually drew.'),
('corporate',3,'A Gantt chart plots tasks against what?','["Cost","Time","Risk","People"]',1,'Henry Gantt drew his by hand in 1910; every bar had to be redrawn when a date moved.'),
('corporate',3,'What did the word "deadline" originally describe?','["A printing cut-off","A railway timetable","A prison boundary","A ship’s waterline"]',2,'Prisoners who crossed the line at a Civil War camp were shot, which is a firmer deadline than most.'),
('corporate',3,'Brainstorming was popularised by someone working in…','["Engineering","Medicine","Teaching","Advertising"]',3,'Alex Osborn set out the rules in 1953; studies since suggest people generate more ideas alone.'),
('corporate',4,'The QWERTY layout was originally designed partly to…','["Speed up typing","Reduce typewriter jams","Alphabetize keys","Fit smaller desks"]',1,'It spaced out common letter pairs so mechanical arms wouldn''t collide.'),
('corporate',4,'In which decade did the first office cubicle debut?','["1950s","1970s","1960s","1980s"]',2,'Designer Robert Propst called later cramped versions "monolithic insanity" and regretted the invention.'),
('corporate',4,'Which company was founded to sell playing cards?','["Nintendo","Samsung","Panasonic","Konami"]',0,'It also ran taxis and a chain of love hotels before deciding that toys were the better business.'),
('corporate',4,'The Post-it note began as a failed attempt to make…','["A cleaning spray","A stronger glue","A whiteboard film","A paper coating"]',1,'The weak adhesive sat unused for years until a colleague wanted a bookmark that would stay put.'),
('corporate',4,'Which company began as a grocery trader selling dried fish and noodles?','["Hyundai","LG","Samsung","Kia"]',2,'The name means "three stars", chosen to suggest something big and everlasting.'),
('corporate',4,'The "elevator pitch" takes its name from…','["A lift maker''s advert","A stock exchange floor","A famous 1920s speech","The length of a lift ride"]',3,'The premise is that you have caught the one person you needed, and roughly thirty seconds of them.'),
('corporate',4,'Which company sold the first commercial photocopier?','["Xerox","Canon","Kodak","Ricoh"]',0,'Market research advised against it: nobody could see why an office would need copies of anything.'),
('corporate',4,'What did Berkshire Hathaway originally manufacture?','["Farm machinery","Textiles","Railway parts","Furniture"]',1,'Warren Buffett has called buying the failing mill the worst investment decision he ever made.'),
('corporate',4,'Which company''s chief executive wrote "Only the Paranoid Survive"?','["Apple","Sony","Intel","Dell"]',2,'Andy Grove had already bet the company once, abandoning memory chips for processors.'),
('corporate',4,'Which car maker started out building weaving looms?','["Honda","Mazda","Nissan","Toyota"]',3,'The loom business was sold to fund the first cars, and the family changed a letter of its name.'),
-- 📼 Rewind
('rewind',1,'Which 90s virtual pet died if you didn''t feed it?','["Furby","Tamagotchi","Pikachu","Beanie Baby"]',1,'Over 82 million Tamagotchis have been sold; some schools banned them for causing "funerals".'),
('rewind',1,'Finish the title: The Fresh Prince of ___','["Beverly Hills","Brooklyn","Bel-Air","Burbank"]',2,'Will Smith took the role partly to pay off a massive tax bill.'),
('rewind',1,'Which toy is a coloured cube you twist to solve?','["Rubik''s Cube","Etch A Sketch","Slinky","Simon"]',0,'Its inventor took a month to solve his own prototype after he had finished building it.'),
('rewind',1,'Which company makes the Mario games?','["Sega","Nintendo","Sony","Capcom"]',1,'Mario wears a cap and moustache because early hardware could not draw hair or a mouth.'),
('rewind',1,'What was a portable CD player commonly called?','["Boombox","Ghetto blaster","Discman","Hi-fi"]',2,'Anti-skip buffers arrived late; before them, walking with one was largely optimistic.'),
('rewind',1,'Which cartoon featured four pizza-loving turtles?','["ThunderCats","He-Man","Biker Mice from Mars","Ninja Turtles"]',3,'They began as a black-and-white comic parody, drawn for an adult audience.'),
('rewind',1,'In which board game do you buy property and build hotels?','["Monopoly","Cluedo","Risk","Scrabble"]',0,'An earlier version was designed to teach players that landlords ruin everyone — the lesson did not land.'),
('rewind',1,'What did a dial-up modem famously do while connecting?','["Flash a green light","Screech and hiss","Print a receipt","Warm up slowly"]',1,'The noise is two modems negotiating a speed; once agreed, they stopped and went quiet.'),
('rewind',1,'Which drink was marketed as "the Uncola"?','["Fanta","Tango","7 Up","Irn-Bru"]',2,'The campaign sold it entirely on not being the thing everyone else was drinking.'),
('rewind',1,'Which home video format outlasted Betamax?','["LaserDisc","Video 2000","MiniDV","VHS"]',3,'It won on tape length rather than picture quality — three hours beat one.'),
('rewind',2,'Which falling-block game came bundled with the original Game Boy?','["Snake","Pac-Man","Breakout","Tetris"]',3,'Bundling Tetris instead of Mario is credited with selling the Game Boy to adults.'),
('rewind',2,'What was Microsoft''s animated paperclip assistant called?','["Clippy","Binky","Pixel","Wordy"]',0,'His official name was Clippit. Almost nobody has ever used it.'),
('rewind',2,'Which company made the Walkman?','["Sony","Panasonic","Sharp","Aiwa"]',0,'Early models had two headphone jacks, because nobody assumed you would want to listen alone.'),
('rewind',2,'Which company made the Mega Drive console?','["Atari","Sega","NEC","SNK"]',1,'Its American advertising attacked a named rival directly, which was almost unheard of at the time.'),
('rewind',2,'Which band released the album "Nevermind"?','["Pearl Jam","Soundgarden","Nirvana","Alice in Chains"]',2,'The baby on the cover was paid two hundred dollars, and has since had opinions about it.'),
('rewind',2,'Which band sang "Wonderwall"?','["Blur","Pulp","Suede","Oasis"]',3,'The title was borrowed from a 1968 film soundtrack by George Harrison.'),
('rewind',2,'Which company made the Game Gear?','["Sega","Nintendo","Atari","Sony"]',0,'It had a colour screen years before its rival, and ate six batteries in about four hours.'),
('rewind',2,'Which artist released the album "Thriller"?','["Prince","Michael Jackson","Lionel Richie","Stevie Wonder"]',1,'Its title video ran fourteen minutes and opened with a disclaimer about the occult.'),
('rewind',2,'Which toy line featured a character called Optimus Prime?','["ThunderCats","M.A.S.K.","Transformers","Voltron"]',2,'The toys were two existing Japanese lines, rebranded and given a single story to share.'),
('rewind',2,'Which band recorded "Africa" in 1982?','["Journey","Foreigner","Chicago","Toto"]',3,'None of them had been to the continent; the lyrics were written from television footage.'),
('rewind',3,'In which year did Google launch?','["1996","2000","1998","2002"]',2,'It started in a rented garage that Google later bought for nostalgia.'),
('rewind',3,'Which group sang "I Want It That Way" (1999)?','["NSYNC","Boyz II Men","Westlife","Backstreet Boys"]',3,'The songwriters barely spoke English — which is why the lyrics famously make no sense.'),
('rewind',3,'In which year did the original Game Boy launch?','["1989","1991","1993","1995"]',0,'One survived a bombing in the Gulf War, and the scorched unit still switches on.'),
('rewind',3,'In which year did the PlayStation 2 launch?','["1998","2000","2002","2004"]',1,'It doubled as a DVD player, which for many households was the actual reason to buy one.'),
('rewind',3,'In which year was the first Harry Potter book published?','["1993","1995","1997","1999"]',2,'The first print run was five hundred copies, and most went straight to libraries.'),
('rewind',3,'Which company created Barbie?','["Hasbro","Bandai","Tomy","Mattel"]',3,'She was based on a German novelty doll sold to adults, which the company quietly redesigned.'),
('rewind',3,'Which toy caused shop stampedes at Christmas in 1996?','["Tickle Me Elmo","Buzz Lightyear","Beanie Babies","Polly Pocket"]',0,'It cost thirty dollars in shops and was resold for over a thousand at the peak of the panic.'),
('rewind',3,'Which console came with an analogue stick as standard?','["Sega Saturn","Nintendo 64","PlayStation","3DO"]',1,'Its rival responded within a year by bolting two sticks onto a controller it had already shipped.'),
('rewind',3,'How many songs did the first iPod promise in your pocket?','["100","500","1,000","5,000"]',2,'The slogan mattered more than the number — rivals were still quoting megabytes.'),
('rewind',3,'In which decade did the compact disc first go on sale?','["1990s","1970s","2000s","1980s"]',3,'The disc was reportedly sized to hold a whole symphony without turning it over.'),
('rewind',4,'What was the best-selling single of the 1990s worldwide?','["Candle in the Wind 1997","...Baby One More Time","My Heart Will Go On","Wannabe"]',0,'Elton John''s Diana tribute sold 33 million copies; he has never performed it again.'),
('rewind',4,'What did the first-ever SMS text message (1992) say?','["Hello","Merry Christmas","Test","Happy New Year"]',1,'Engineer Neil Papworth sent it from a computer — phones couldn''t type text yet.'),
('rewind',4,'Nintendo''s Virtual Boy was notorious for…','["Displaying only red","Costing under fifty","Selling out instantly","Using no cartridges"]',0,'It was discontinued within a year, and came with a warning about how long children could play.'),
('rewind',4,'What colour was the original Game Boy''s screen?','["Blue","Green","Grey","Amber"]',1,'The olive tint came from the cheap reflective display, not from any design decision.'),
('rewind',4,'What was Pepsi''s short-lived clear cola called?','["Pepsi Ice","Pepsi Blue","Crystal Pepsi","Pepsi Light"]',2,'It tasted like cola but looked like lemonade, and shoppers found that combination unsettling.'),
('rewind',4,'What was the Mega Drive called in North America?','["Sega Master System","Sega Saturn","Sega Mega CD","Sega Genesis"]',3,'The name changed because another company already held the European trademark.'),
('rewind',4,'What was the Furby advertised as doing over time?','["Gradually speaking English","Recharging from sunlight","Connecting to a telephone","Changing colour with heat"]',0,'It was pre-programmed to shift languages on a timer; it never listened to a word you said.'),
('rewind',4,'The name "SEGA" was shortened from…','["Sound Engineering","Service Games","Sega Enterprises","Second Generation"]',1,'The company began by supplying coin-operated machines to American military bases in Japan.'),
('rewind',4,'What was the Rubik''s Cube originally called?','["The Puzzle Box","The Magic Ball","The Magic Cube","The Twist Cube"]',2,'It was renamed for export, after its Hungarian inventor, when a toy firm licensed it.'),
('rewind',4,'What was the Nintendo Wii called before release?','["Dolphin","Project Reality","Ultra 64","Revolution"]',3,'The final name was chosen to work in every language, and was mocked in every language.'),
-- 🐸 Extremely Online
('online',1,'What breed of dog is the "Doge" meme?','["Corgi","Akita","Pomeranian","Shiba Inu"]',3,'The real dog, Kabosu, was a rescue from a Japanese puppy mill.'),
('online',1,'What does "LOL" stand for?','["Laughing out loud","Lots of love","Log off later","Loudly on line"]',0,'Countless parents have signed condolence texts "LOL" thinking it meant lots of love.'),
('online',1,'What does "BRB" mean online?','["Be right back","Bring roughly back","Been really busy","By the by"]',0,'It survived from chat rooms where leaving without warning read as walking out mid-sentence.'),
('online',1,'What is a "selfie"?','["A group portrait","A photo of yourself","A camera setting","A photo filter"]',1,'The word first appeared in an Australian online forum, in a post apologising for a blurry photo.'),
('online',1,'What does adding a hashtag to a post do?','["Deletes it later","Hides it from friends","Groups it by topic","Sends it privately"]',2,'No platform designed it — a user suggested borrowing the symbol from chat channels.'),
('online',1,'What does "DM" stand for?','["Data mode","Daily message","Double mention","Direct message"]',3,'Sliding into them is a phrase barely a decade old, and it already sounds dated.'),
('online',1,'What is an emoji?','["A small picture","A short video","A sound clip","A link preview"]',0,'The name is Japanese for "picture character" and has nothing to do with the word emotion.'),
('online',1,'What does it mean for a post to "go viral"?','["To be deleted","To spread rapidly","To be reported","To load slowly"]',1,'The metaphor is literal enough that epidemiologists study both with the same equations.'),
('online',1,'What does "IRL" stand for?','["In rare loops","I really like","In real life","Instantly reloaded"]',2,'The phrase implies the other place is not real, which fewer people would now agree with.'),
('online',1,'What is a "thread" on social media?','["A private group","A blocked user","A saved draft","A series of posts"]',3,'The word came from 1980s message boards, where replies were literally strung together.'),
('online',2,'The "Distracted Boyfriend" meme is originally what?','["A movie still","A stock photo","A music video frame","A news photo"]',1,'The same models appear in dozens of stock photos, forming an accidental cinematic universe.'),
('online',2,'Which platform''s logo was a bird until 2023?','["Snapchat","Telegram","Twitter","Tumblr"]',2,'The bird''s official name was Larry, after basketball legend Larry Bird.'),
('online',2,'Which platform is built around short vertical videos?','["TikTok","Reddit","LinkedIn","Flickr"]',0,'It grew out of a lip-syncing app that was folded into it, taking its users along.'),
('online',2,'Which platform is built around live game streaming?','["Vimeo","Twitch","Flickr","Pinterest"]',1,'It began as a spin-off of a site where one man broadcast his entire life from a head camera.'),
('online',2,'A "Rickroll" sends you to a song by whom?','["Rick James","Rick Springfield","Rick Astley","Rick Ross"]',2,'He has said he finds it funny, and re-recorded the song decades later to lean into it.'),
('online',2,'Which platform popularised the "story" that disappears?','["Reddit","Tumblr","LinkedIn","Snapchat"]',3,'Every large rival copied the format within four years, mostly without changing the name.'),
('online',2,'Which file format is used for short looping animations?','["GIF","PNG","MP3","PDF"]',0,'It was designed in 1987 for slow modems, and outlived every format meant to replace it.'),
('online',2,'Which site is built around pinning images to boards?','["Flickr","Pinterest","Imgur","DeviantArt"]',1,'It ran invite-only for its first two years, which is unusual for something that visual.'),
('online',2,'"Doomscrolling" means reading what, endlessly?','["Old messages","Product reviews","Bad news","Terms of service"]',2,'The word spread in 2020, but the behaviour it names is as old as the rolling news ticker.'),
('online',2,'Which chat app is organised into servers and voice channels?','["Slack","Telegram","Signal","Discord"]',3,'It was built for gamers who needed to talk while playing, then everyone else moved in.'),
('online',3,'What was the first YouTube video about?','["A cat playing piano","Elephants at the zoo","A dance tutorial","A video game"]',1,'"Me at the zoo" (2005) is 19 seconds long and still up.'),
('online',3,'Who coined the word "meme" in 1976?','["Douglas Adams","Carl Sagan","Richard Dawkins","Marshall McLuhan"]',2,'He meant it as the cultural equivalent of a gene — cat pictures came later.'),
('online',3,'In which year did YouTube launch?','["2005","2007","2009","2011"]',0,'It was bought by Google within twenty months, before it had made any money at all.'),
('online',3,'The "This is fine" dog comes from which webcomic?','["xkcd","Gunshow","Perry Bible Fellowship","Cyanide & Happiness"]',1,'In the full strip the dog melts — the calm two panels everyone shares are only the setup.'),
('online',3,'The Nyan Cat had a body made of what?','["A doughnut","A waffle","A Pop-Tart","A pancake"]',2,'The animation and the song were made by two different people who had never worked together.'),
('online',3,'In which year did Instagram launch?','["2006","2008","2012","2010"]',3,'It started as a check-in app with photos bolted on, and everything else was stripped out.'),
('online',3,'The "Harlem Shake" videos used a track by which producer?','["Baauer","Skrillex","Diplo","Flosstradamus"]',0,'The dance in the videos is not the Harlem Shake, and dancers from Harlem said so loudly.'),
('online',3,'"Charlie bit my finger" was uploaded to share with…','["A news website","The boys'' godfather","A school class","A camera forum"]',1,'It was set to public only because the family could not work out how to send a large file.'),
('online',3,'Grumpy Cat''s expression was caused by…','["A bad temper","The camera angle","A form of dwarfism","A rare eye colour"]',2,'Her owners insisted she was friendly; the face was simply the face she had.'),
('online',3,'In which year did Wikipedia launch?','["1997","1999","2003","2001"]',3,'It began as a side project to feed a slower encyclopaedia written only by experts.'),
('online',4,'As of 2020, the most-retweeted post ever was…','["Ellen''s Oscar selfie","A plea for chicken nuggets","An Obama quote","A Japanese billionaire''s cash giveaway"]',3,'Yusaku Maezawa offered ¥100m to random retweeters — 4+ million obliged.'),
('online',4,'Keyboard Cat''s original footage was recorded in which decade?','["1980s","1990s","2000s","2010s"]',0,'Charlie Schmidt filmed his cat Fatso in 1984; the internet found it 23 years later.'),
('online',4,'The "Success Kid" photo was taken where?','["On a beach","In a garden","At a party","In a kitchen"]',0,'He is not celebrating anything — he is about to eat a handful of sand.'),
('online',4,'What is the name of Reddit''s mascot?','["Reddy","Snoo","Alien","Karma"]',1,'The name is a pun on "what''s new", which is roughly what the whole site is for.'),
('online',4,'The "Dancing Baby" animation spread in which decade?','["1970s","1980s","1990s","2000s"]',2,'It was a sample file bundled with 3D software, forwarded by email until it reached television.'),
('online',4,'What was YouTube originally built to be?','["A file host","A photo album","A gaming site","A dating site"]',3,'Nobody uploaded any dating videos, so the founders opened it to whatever people had.'),
('online',4,'The hashtag was first proposed by a user of which platform?','["Twitter","Flickr","MySpace","Digg"]',0,'The company initially thought it looked too technical for ordinary people to bother with.'),
('online',4,'The first photograph put on the web showed…','["A cat","A comedy band","A sunset","A circuit board"]',1,'They were a group of physicists at CERN, and the web was barely a year old at the time.'),
('online',4,'The "Numa Numa" video used a song by which band?','["Eiffel 65","Aqua","O-Zone","Cascada"]',2,'The song is Romanian, and the man in the video was filming himself in his bedroom.'),
('online',4,'What was Twitter originally called?','["Chirp","Status","Friendstalker","twttr"]',3,'Vowels were dropped to fit a five-character text short code, the way other services did then.'),
-- ☕ Fuel
('fuel',1,'Espresso was invented in which country?','["Italy","France","Spain","Brazil"]',0,'The word means "pressed out" — not "express", though it is faster.'),
('fuel',1,'Sushi is traditionally wrapped in…','["Seaweed (nori)","Rice paper","Lettuce","Banana leaf"]',0,'Nori was once scraped off dock posts; now it''s farmed on huge ocean nets.'),
('fuel',1,'Which fruit is dried to make a raisin?','["Grape","Plum","Fig","Date"]',0,'A dried plum is a prune, which is the same trick under a name nobody enjoys as much.'),
('fuel',1,'Guacamole is made mainly from what?','["Peas","Avocado","Courgette","Spinach"]',1,'The fruit ripens only after picking, which is why growers can leave it on the tree for months.'),
('fuel',1,'Which grain is ordinary bread flour milled from?','["Rice","Maize","Wheat","Barley"]',2,'Its gluten is what traps the gas from yeast; without that, bread simply stays flat.'),
('fuel',1,'Which nut is marzipan made from?','["Walnut","Pecan","Cashew","Almond"]',3,'Bitter varieties of the same nut contain traces of cyanide, so sweet ones are used instead.'),
('fuel',1,'Mozzarella was traditionally made from the milk of which animal?','["Buffalo","Goat","Sheep","Camel"]',0,'The herds were kept on marshland where cattle struggled, which is how the tradition started.'),
('fuel',1,'Which spice gives curry powder its yellow colour?','["Paprika","Turmeric","Cumin","Saffron"]',1,'It stains almost everything it touches, and was used as a fabric dye long before a kitchen wanted it.'),
('fuel',1,'Tofu is made from which bean?','["Kidney","Broad","Soya","Black"]',2,'It is made much like cheese — the milk is curdled, then the curds are pressed into a block.'),
('fuel',1,'Which vegetable is the main ingredient of kimchi?','["Carrot","Potato","Onion","Cabbage"]',3,'It was buried in jars through the winter, which is exactly how the fermentation was controlled.'),
('fuel',2,'Which coffee chain is named after a Moby-Dick character?','["Costa","Peet''s","Starbucks","Lavazza"]',2,'The founders almost named it Pequod, after the ship. "Starbuck" was the first mate.'),
('fuel',2,'Croissants originated in which country?','["France","Belgium","Switzerland","Austria"]',3,'The Viennese kipferl came first; France laminated it with butter and took the credit.'),
('fuel',2,'Paella comes from which country?','["Spain","Italy","Portugal","Greece"]',0,'The name is the pan, not the dish — and the crust stuck to its bottom is the prized part.'),
('fuel',2,'Goulash is a dish from which country?','["Poland","Hungary","Austria","Romania"]',1,'It began as herdsmen’s food, dried into blocks so it could be carried and rehydrated later.'),
('fuel',2,'Feta cheese comes from which country?','["Turkey","Bulgaria","Greece","Cyprus"]',2,'The name is legally protected, so a similar cheese made elsewhere has to be called something else.'),
('fuel',2,'Pad thai is the national dish of which country?','["Vietnam","Malaysia","Cambodia","Thailand"]',3,'It was promoted by the government in the 1930s, partly to reduce how much rice the country ate.'),
('fuel',2,'What does "al dente" describe?','["Firm to the bite","Cooked in butter","Served very hot","Sliced very thin"]',0,'The phrase means "to the tooth", and the firmness is a texture judgement, not a timing one.'),
('fuel',2,'Ceviche is associated with which country?','["Chile","Peru","Mexico","Ecuador"]',1,'The fish is not cooked with heat at all — acid from the citrus firms the flesh instead.'),
('fuel',2,'What does "umami" describe?','["A cooking method","A cutting style","A savoury taste","A serving size"]',2,'It was identified in 1908 but only accepted as a fifth basic taste around a century later.'),
('fuel',2,'Biryani is a rice dish from which country?','["Thailand","Malaysia","Indonesia","India"]',3,'The pot is often sealed shut with dough, so the rice finishes cooking in trapped steam.'),
('fuel',3,'After water, the most-consumed drink in the world is…','["Tea","Coffee","Beer","Orange juice"]',0,'Roughly 2 billion cups of tea are drunk every day.'),
('fuel',3,'Nutella''s main nut is the…','["Almond","Hazelnut","Peanut","Cashew"]',1,'Nutella uses about a quarter of the world''s hazelnut supply.'),
('fuel',3,'Botanically, a tomato is a…','["Fruit","Root","Tuber","Grain"]',0,'A US court once ruled it a vegetable anyway, because the case was really about import taxes.'),
('fuel',3,'Cinnamon is which part of a tree?','["The root","The bark","The seed","The flower"]',1,'It curls into quills as it dries, which is why the sticks have that shape at all.'),
('fuel',3,'Where do peanuts grow?','["On tall trees","On climbing vines","Under the ground","On low bushes"]',2,'The flower bends down after pollination and pushes itself into the soil to finish the job.'),
('fuel',3,'A caper is which part of a plant?','["A dried seed","A young root","A curled leaf","A flower bud"]',3,'Left alone it opens into a large white flower, which is why the harvest window is so short.'),
('fuel',3,'Which country grows the most coffee?','["Brazil","Colombia","Vietnam","Ethiopia"]',0,'It has led the world for over a century, and a single bad frost there moves the global price.'),
('fuel',3,'White chocolate contains none of what?','["Milk powder","Cocoa solids","Cane sugar","Vanilla flavour"]',1,'It uses the cocoa butter and leaves out the rest, which is why several countries argued over the name.'),
('fuel',3,'A banana plant is botanically a…','["Tree","Bush","Herb","Vine"]',2,'The trunk is not wood but tightly packed leaf bases, which is why one storm can flatten a field.'),
('fuel',3,'How long can sealed honey stay edible?','["A year","A decade","A century","Indefinitely"]',3,'Jars found in Egyptian tombs were still unspoiled — it is too acidic and too dry for microbes.'),
('fuel',4,'Which country drinks the most coffee per capita?','["USA","Italy","Brazil","Finland"]',3,'Finns average 8–12 kg of coffee per person per year; coffee breaks are protected in many union contracts.'),
('fuel',4,'Carrots were originally mostly what color?','["Purple","Orange","White","Red"]',0,'Dutch growers bred orange carrots in the 1600s, allegedly honoring William of Orange.'),
('fuel',4,'Which chemical makes chillies taste hot?','["Capsaicin","Piperine","Allicin","Menthol"]',0,'It binds to the receptor that detects heat, so the burn is a genuine false alarm.'),
('fuel',4,'Which country did the potato originally come from?','["Ireland","Peru","Poland","Spain"]',1,'Thousands of varieties are still grown in the Andes, in colours no supermarket stocks.'),
('fuel',4,'What is the main flavour compound in vanilla called?','["Eugenol","Limonene","Vanillin","Linalool"]',2,'Most of what is sold is made in a factory, because the orchid has to be pollinated by hand.'),
('fuel',4,'Which fruit was once called a "love apple"?','["Peach","Quince","Pomegranate","Tomato"]',3,'Europeans avoided eating it for two centuries, convinced the whole plant was poisonous.'),
('fuel',4,'How many chambers does a cow''s stomach have?','["Four","Two","Three","Seven"]',0,'Only the last one digests like ours; the first three are essentially a fermentation vat.'),
('fuel',4,'Which drink was first sold as a remedy for headaches?','["Lucozade","Coca-Cola","Dr Pepper","Lemonade"]',1,'It was sold by the glass at a pharmacy counter, and the fizzy water was added at the last step.'),
('fuel',4,'Which spice comes from the stigma of a crocus flower?','["Cardamom","Turmeric","Saffron","Sumac"]',2,'It takes about 150,000 flowers to make a kilogram, which is why it outprices silver.'),
('fuel',4,'Which of these is botanically a berry?','["Strawberry","Raspberry","Blackberry","Banana"]',3,'The three that carry the name are not berries at all, which the botanists find funnier than we do.')
on conflict (category, prompt) where room_id is null do update set
  tier = excluded.tier,
  options = excluded.options,
  correct_index = excluded.correct_index,
  fun_fact = excluded.fun_fact;
